"""user_id in Wishlist model

Revision ID: d3616d56b8b2
Revises: b905c70f65ad
Create Date: 2024-12-26 14:31:18.756762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3616d56b8b2'
down_revision: Union[str, None] = 'b905c70f65ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wishlist', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.drop_column('wishlist', 'user_id')
    # ### end Alembic commands ###
